Name:           perl-Devel-Callsite
Version:        1.0.1
Release:        5%{?dist}
Summary:        Get caller return OP address and Perl interpreter context
License:        GPLv2+ or Artistic
URL:            https://metacpan.org/release//Devel-Callsite
Source0:        https://cpan.metacpan.org/authors/id/R/RO/ROCKY/Devel-Callsite-%{version}.tar.gz

BuildRequires:  gcc
BuildRequires:  perl(:VERSION) >= 5.5.0
BuildRequires:  perl-devel
BuildRequires:  perl-generators
BuildRequires:  perl-interpreter
BuildRequires:  perl(B)
BuildRequires:  perl(Exporter)
BuildRequires:  perl(ExtUtils::MakeMaker)
BuildRequires:  perl(Test::More)
BuildRequires:  perl(XSLoader)
BuildRequires:  perl(base)
BuildRequires:  perl(strict)
BuildRequires:  perl(vars)
BuildRequires:  perl(warnings)

Requires:       perl(:MODULE_COMPAT_%(perl -V:version | sed 's,[^0-9^.]*,,g'))

%description
Get caller return OP address and Perl interpreter context.

%prep
%setup -q -n Devel-Callsite-%{version}

%build
perl Makefile.PL INSTALLDIRS=vendor OPTIMIZE="$RPM_OPT_FLAGS" NO_PACKLIST=1 NO_PERLLOCAL=1
%make_build

%install
%make_install

%{_fixperms} $RPM_BUILD_ROOT/*

%check
make test

%files
%license Artistic gpl-2.0.txt
%doc Changes README
%{perl_vendorarch}/auto/*
%{perl_vendorarch}/Devel*
%{_mandir}/man3/*

%changelog
* Mon Jun 22 2020 Jitka Plesnikova <jplesnik@redhat.com> - 1.0.1-5
- Perl 5.32 rebuild

* Wed Jan 29 2020 Fedora Release Engineering <releng@fedoraproject.org> - 1.0.1-4
- Rebuilt for https://fedoraproject.org/wiki/Fedora_32_Mass_Rebuild

* Mon Nov 11 2019 Yanko Kaneti <yaneti@declera.com> - 1.0.1-3
- Specfile autogenerated by cpanspec 1.78 and tweaked
- Additional fixes as per review -2
- One last review TODO -3