Name:           perl-Text-xSV
Version:        0.21
Release:        6%{?dist}
Summary:        Read character separated files
License:        GPL+ or Artistic

URL:            https://metacpan.org/release/Text-xSV
Source0:        https://cpan.metacpan.org/authors/id/T/TI/TILLY/Text-xSV-%{version}.tar.gz

BuildArch:      noarch
BuildRequires:  perl-interpreter
BuildRequires:  perl-generators
BuildRequires:  perl(Cwd)
BuildRequires:  perl(ExtUtils::MakeMaker)
BuildRequires:  perl(File::Basename)
BuildRequires:  perl(File::Spec)
BuildRequires:  perl(Module::Build)
# run requirements
BuildRequires:  perl(Carp)
BuildRequires:  perl(strict)

Requires:       perl(:MODULE_COMPAT_%(perl -V:version | sed 's,[^0-9^.]*,,g'))

%{?perl_default_filter}

%description
This module is for reading and writing a common variation of character
separated data. The most common example is comma-separated. However that is
far from the only possibility, the same basic format is exported by
Microsoft products using tabs, colons, or other characters.

%prep
%setup -q -n Text-xSV-%{version}

%build
%{__perl} Build.PL --installdirs=vendor
./Build

%install
./Build install --destdir=$RPM_BUILD_ROOT --create_packlist=0
%{_fixperms} $RPM_BUILD_ROOT/*

%check
%{__perl} -Ilib test.pl
# ./Build test

%files
%doc Build Changes README test.csv
%{perl_vendorlib}/Text*
%{_mandir}/man3/Text*

%changelog
* Tue Jun 23 2020 Jitka Plesnikova <jplesnik@redhat.com> - 0.21-6
- Perl 5.32 rebuild

* Thu Jan 30 2020 Fedora Release Engineering <releng@fedoraproject.org> - 0.21-5
- Rebuilt for https://fedoraproject.org/wiki/Fedora_32_Mass_Rebuild

* Fri Jul 26 2019 Fedora Release Engineering <releng@fedoraproject.org> - 0.21-4
- Rebuilt for https://fedoraproject.org/wiki/Fedora_31_Mass_Rebuild

* Fri May 31 2019 Jitka Plesnikova <jplesnik@redhat.com> - 0.21-3
- Perl 5.30 rebuild

* Sat Feb 02 2019 Fedora Release Engineering <releng@fedoraproject.org> - 0.21-2
- Rebuilt for https://fedoraproject.org/wiki/Fedora_30_Mass_Rebuild

* Sun Nov 04 2018 Emmanuel Seyman <emmanuel@seyman.fr> 0.21-1
- Initial specfile, based on the one autogenerated by cpanspec 1.78.
