Name:           perl-Exporter-Easy
Version:        0.18
Release:        8%{?dist}
Summary:        Takes the drudgery out of Exporting symbols
License:        GPL+ or Artistic

URL:            https://metacpan.org/release/Exporter-Easy
Source0:        https://cpan.metacpan.org/authors/id/N/NE/NEILB/Exporter-Easy-%{version}.tar.gz

BuildArch:      noarch
BuildRequires:  make
BuildRequires:  perl-interpreter >= 0:5.006
BuildRequires:  perl-generators
BuildRequires:  perl(ExtUtils::MakeMaker) >= 6.76
# Runtime
BuildRequires:  perl(Exporter)
BuildRequires:  perl(strict)
BuildRequires:  perl(vars)
BuildRequires:  perl(warnings)
# Tests
BuildRequires:  perl(Test::More)
BuildRequires:  perl(base)
BuildRequires:  perl(lib)
Requires:       perl(:MODULE_COMPAT_%(eval "`%{__perl} -V:version`"; echo $version))

%{?perl_default_filter}

%description
Exporter::Easy makes using Exporter easy. In its simplest case, it allows
you to drop the boilerplate code that comes with using Exporter, so more
complicated situations where you use tags to build lists and more tags
become easy.

%prep
%setup -q -n Exporter-Easy-%{version}

%build
%{__perl} Makefile.PL INSTALLDIRS=vendor NO_PACKLIST=1
make %{?_smp_mflags}

%install
make pure_install DESTDIR=$RPM_BUILD_ROOT
%{_fixperms} $RPM_BUILD_ROOT/*

%check
make test

%files
%doc Changes README TODO
%license LICENSE
%{perl_vendorlib}/Exporter*
%{_mandir}/man3/Exporter*

%changelog
* Fri Jul 26 2019 Fedora Release Engineering <releng@fedoraproject.org> - 0.18-8
- Rebuilt for https://fedoraproject.org/wiki/Fedora_31_Mass_Rebuild

* Thu May 30 2019 Jitka Plesnikova <jplesnik@redhat.com> - 0.18-7
- Perl 5.30 rebuild

* Fri Feb 01 2019 Fedora Release Engineering <releng@fedoraproject.org> - 0.18-6
- Rebuilt for https://fedoraproject.org/wiki/Fedora_30_Mass_Rebuild

* Fri Jul 13 2018 Fedora Release Engineering <releng@fedoraproject.org> - 0.18-5
- Rebuilt for https://fedoraproject.org/wiki/Fedora_29_Mass_Rebuild

* Wed Jun 27 2018 Jitka Plesnikova <jplesnik@redhat.com> - 0.18-4
- Perl 5.28 rebuild

* Thu Feb 08 2018 Fedora Release Engineering <releng@fedoraproject.org> - 0.18-3
- Rebuilt for https://fedoraproject.org/wiki/Fedora_28_Mass_Rebuild

* Mon Aug 07 2017 Emmanuel Seyman <emmanuel@seyman.fr> - 0.18-2
- Take into account review comments (#1478703)

* Sun Jul 16 2017 Emmanuel Seyman <emmanuel@seyman.fr> - 0.18-1
- Initial specfile, based on the one autogenerated by cpanspec 1.78.
