Name:           perl-Test-NiceDump
Version:        1.0.1
Release:        3%{?dist}
Summary:        Get a nice and human readable dump of objects
License:        GPL+ or Artistic
URL:            https://metacpan.org/release/Test-NiceDump/
Source0:        https://cpan.metacpan.org/authors/id/D/DA/DAKKAR/Test-NiceDump-%{version}.tar.gz
BuildArch:      noarch
BuildRequires:  make
BuildRequires:  perl-generators
BuildRequires:  perl-interpreter
BuildRequires:  perl(ExtUtils::MakeMaker) >= 6.76
BuildRequires:  perl(strict)
BuildRequires:  perl(warnings)
# Run-tiem
BuildRequires:  perl(Data::Dump)
BuildRequires:  perl(Data::Dump::Filtered)
BuildRequires:  perl(Exporter)
BuildRequires:  perl(overload)
BuildRequires:  perl(Safe::Isa) >= 1.000010
BuildRequires:  perl(Test::Builder)
# Tests
BuildRequires:  perl(Test::More)
Requires:       perl(:MODULE_COMPAT_%(perl -V:version | sed 's,[^0-9^.]*,,g'))

%description
This module uses Data::Dump::Filtered and a set of sensible filters to dump
test data in a more readable way.

%prep
%setup -q -n Test-NiceDump-%{version}

%build
perl Makefile.PL INSTALLDIRS=vendor NO_PACKLIST=1 NO_PERLLOCAL=1
%{make_build}

%install
%{make_install}
%{_fixperms} $RPM_BUILD_ROOT/*

%check
unset AUTHOR_TESTING
make test

%files
%license LICENSE
%doc Changes README.md
%{perl_vendorlib}/*
%{_mandir}/man3/*

%changelog
* Tue Jun 23 2020 Jitka Plesnikova <jplesnik@redhat.com> - 1.0.1-3
- Perl 5.32 rebuild

* Thu Jan 30 2020 Fedora Release Engineering <releng@fedoraproject.org> - 1.0.1-2
- Rebuilt for https://fedoraproject.org/wiki/Fedora_32_Mass_Rebuild

* Mon Jul 22 2019 Jitka Plesnikova <jplesnik@redhat.com> - 1.0.1-1
- Specfile autogenerated by cpanspec 1.78.
