Name:           perl-Lingua-EN-PluralToSingular
Version:        0.21
Release:        9%{?dist}
Summary:        Change an English plural to a singular
License:        GPL+ or Artistic

URL:            https://metacpan.org/release/Lingua-EN-PluralToSingular
Source0:        https://cpan.metacpan.org/authors/id/B/BK/BKB/Lingua-EN-PluralToSingular-%{version}.tar.gz

BuildArch:      noarch
# build deps
BuildRequires:  perl-interpreter
BuildRequires:  perl-generators
BuildRequires:  perl(ExtUtils::MakeMaker) >= 6.76
BuildRequires:  perl
# runtime deps
BuildRequires:  perl(Exporter)
BuildRequires:  perl(strict)
BuildRequires:  perl(warnings)
# test deps
BuildRequires:  perl(Test::More)
Requires:       perl(:MODULE_COMPAT_%(perl -V:version | sed 's,[^0-9^.]*,,g'))

%description
This converts words denoting a plural in the English language into words
denoting a singular noun.

%prep
%setup -q -n Lingua-EN-PluralToSingular-%{version}

%build
%{__perl} Makefile.PL INSTALLDIRS=vendor NO_PACKLIST=1
make %{?_smp_mflags}

%install
make pure_install DESTDIR=$RPM_BUILD_ROOT
%{_fixperms} $RPM_BUILD_ROOT/*

%check
make test

%files
# upstream package has no LICENSE file.
# https://github.com/benkasminbullock/Lingua-EN-PluralToSingular/issues/19
%doc Changes README
%{perl_vendorlib}/Lingua*
%{_bindir}/singular
%{_mandir}/man1/singular*
%{_mandir}/man3/Lingua*

%changelog
* Mon Jun 22 2020 Jitka Plesnikova <jplesnik@redhat.com> - 0.21-9
- Perl 5.32 rebuild

* Thu Jan 30 2020 Fedora Release Engineering <releng@fedoraproject.org> - 0.21-8
- Rebuilt for https://fedoraproject.org/wiki/Fedora_32_Mass_Rebuild

* Fri Jul 26 2019 Fedora Release Engineering <releng@fedoraproject.org> - 0.21-7
- Rebuilt for https://fedoraproject.org/wiki/Fedora_31_Mass_Rebuild

* Thu May 30 2019 Jitka Plesnikova <jplesnik@redhat.com> - 0.21-6
- Perl 5.30 rebuild

* Fri Feb 01 2019 Fedora Release Engineering <releng@fedoraproject.org> - 0.21-5
- Rebuilt for https://fedoraproject.org/wiki/Fedora_30_Mass_Rebuild

* Fri Jul 13 2018 Fedora Release Engineering <releng@fedoraproject.org> - 0.21-4
- Rebuilt for https://fedoraproject.org/wiki/Fedora_29_Mass_Rebuild

* Wed Jun 27 2018 Jitka Plesnikova <jplesnik@redhat.com> - 0.21-3
- Perl 5.28 rebuild

* Sun Jun 24 2018 Emmanuel Seyman <emmanuel@seyman.fr> - 0.21-2
- Fix manpage declaration

* Sun Jun 24 2018 Emmanuel Seyman <emmanuel@seyman.fr> - 0.21-1
- Update to 0.21

* Sun Jun 17 2018 Emmanuel Seyman <emmanuel@seyman.fr> - 0.19-2
- Take into account review comments (#1592135)

* Thu Apr 12 2018 Emmanuel Seyman <emmanuel@seyman.fr> - 0.19-1
- Initial specfile, based on the one autogenerated by cpanspec 1.78.
