Name:           perl-Syntax-Keyword-Gather
Version:        1.003002
Release:        6%{?dist}
Summary:        Implements the Perl 6 'gather/take' control structure in Perl 5
License:        GPL+ or Artistic

URL:            https://metacpan.org/release/Syntax-Keyword-Gather/
Source0:        https://cpan.metacpan.org/authors/id/F/FR/FREW/Syntax-Keyword-Gather-%{version}.tar.gz

BuildArch:      noarch
# build deps
BuildRequires:  perl-interpreter
BuildRequires:  perl-generators
BuildRequires:  perl(ExtUtils::MakeMaker) >= 6.76
BuildRequires:  perl(strict)
BuildRequires:  perl(warnings)
BuildRequires:  perl
# runtime deps
BuildRequires:  perl(Carp)
BuildRequires:  perl(Sub::Exporter::Progressive)
BuildRequires:  perl(overload)
# test deps
BuildRequires:  perl(Test::More) >= 0.94
BuildRequires:  perl(Test::Pod)
Requires:       perl(:MODULE_COMPAT_%(eval "`%{__perl} -V:version`"; echo $version))

%{?perl_default_filter}

%description
Perl 6 provides a new control structure -- gather -- that allows lists to
be constructed procedurally, without the need for a temporary variable.
Within the block/closure controlled by a gather any call to take pushes
that call's argument list to an implicitly created array. take returns the
number of elements it took. This module implements that control structure.

%prep
%setup -q -n Syntax-Keyword-Gather-%{version}

%build
%{__perl} Makefile.PL INSTALLDIRS=vendor NO_PACKLIST=1
make %{?_smp_mflags}

%install
make pure_install DESTDIR=$RPM_BUILD_ROOT
%{_fixperms} $RPM_BUILD_ROOT/*

%check
make test

%files
%doc Changes README
%license LICENSE
%{perl_vendorlib}/Syntax*
%{_mandir}/man3/Syntax*

%changelog
* Fri Jul 26 2019 Fedora Release Engineering <releng@fedoraproject.org> - 1.003002-6
- Rebuilt for https://fedoraproject.org/wiki/Fedora_31_Mass_Rebuild

* Fri May 31 2019 Jitka Plesnikova <jplesnik@redhat.com> - 1.003002-5
- Perl 5.30 rebuild

* Sat Feb 02 2019 Fedora Release Engineering <releng@fedoraproject.org> - 1.003002-4
- Rebuilt for https://fedoraproject.org/wiki/Fedora_30_Mass_Rebuild

* Fri Jul 13 2018 Fedora Release Engineering <releng@fedoraproject.org> - 1.003002-3
- Rebuilt for https://fedoraproject.org/wiki/Fedora_29_Mass_Rebuild

* Thu Jun 28 2018 Jitka Plesnikova <jplesnik@redhat.com> - 1.003002-2
- Perl 5.28 rebuild

* Tue Jun 19 2018 Emmanuel Seyman <emmanuel@seyman.fr> - 1.003002-1
- Initial specfile, based on the one autogenerated by cpanspec 1.78.
